import Head from "next/head";
import Header from "../components/header";
import Layout from "../components/layout";
import image from "../public/hero.jpg";
import styles from "./index.module.css";
export default function IndexPage() {
  return (
    <Layout>
      <Head>
        <title>ESO Daily Tracker</title>
        <meta name="ESO Daily Tracker" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
          <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png"/>
      </Head>
      <div className={`${styles.home}   h-screen `}>
        <div className="absolute left-1/2 -translate-x-1/2"></div>
        <div className="absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 ">
          <div className="text-6xl text-white">ESO Daily Tracker</div>
        </div>
      </div>
    </Layout>
  );
}
