name: Trigger Site Rebuild on a CRON Schedule

on:
  push:
    branches:
      - master


jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request POST \
          --url 'https://esodailytracker.vercel.app/api/example' \
          --header 'Authorization:${{secrets.ACTION_KEY}}'
