name: Trigger prisma weekly reset on a CRON Schedule

on:
  schedule:
    # Runs "11:00 am utc on mondays (2am est)" (see https://crontab.guru)
    - cron: '0 6 * * 1'


jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request POST \
          --url 'https://esodailytracker.vercel.app/api/weeklyreset' \
          --header 'Authorization:${{secrets.ACTION_KEY}}'
